# Generated by Django 4.1.5 on 2023-01-26 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 1, 26, 2, 32, 44, 2279, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
