# Generated by Django 4.1.5 on 2023-01-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('cohort', models.CharField(max_length=32)),
                ('favorite_language', models.CharField(max_length=32)),
                ('capstone', models.CharField(max_length=32)),
            ],
        ),
    ]
