# Generated by Django 4.1.5 on 2023-01-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='capstone',
            field=models.URLField(max_length=100),
        ),
    ]
