# Generated by Django 4.1.4 on 2022-12-31 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 12, 31, 3, 35, 38, 512834, tzinfo=datetime.timezone.utc)),
        ),
    ]
