# Generated by Django 4.1.4 on 2022-12-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0002_remove_todoitem_completed_date_todoitem_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='date_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
