# Generated by Django 4.1.4 on 2022-12-25 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0004_rename_text_todoitem_task_todoitem_item_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
