# Generated by Django 4.1.4 on 2022-12-25 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0005_alter_todoitem_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
