# Generated by Django 4.1.4 on 2022-12-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0006_todoitem_time_alter_todoitem_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='time',
            new_name='time_due',
        ),
    ]
