# Generated by Django 4.1.4 on 2022-12-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_todoitem_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
