# Generated by Django 4.1.5 on 2023-01-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('cohort', models.CharField(max_length=50)),
                ('fav_language', models.CharField(max_length=25)),
                ('capstone', models.URLField()),
            ],
        ),
    ]
